name: Publish Package

on:
  push:
    tags:        
      - v[0].[0-9]+.[0-9]+

jobs:
  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.IDEALJS_BOT_APP_ID }}
          private_key: ${{ secrets.IDEALJS_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Test Packages
        run: yarn workspaces foreach run test
      - name: Update Version
        run: yarn workspaces foreach -A $GITHUB_REF_NAME
      - name: Publish Package
        run: yarn workspaces foreach -A npm publish
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ failure() && steps.e2e.conclusion == 'failure' }}
        with:
          commit_message: 'chore: update image snapshot'
